import { decodeBase64 } from "@/app/lib/decodeBase64";
import { expect, test } from "vitest";

const tests = [
  [
    "T2JqZXRvIHNvY2lhbDogTGEgc29jaWVkYWQgdGllbmUgcG9yIG9iamV0byBsYSBwcm9kdWNjacOzbiwgaW5kdXN0cmlhbGl6YWNpw7NuIHkgY29tZXJjaWFsaXphY2nDs24gZGUgcHJvZHVjdG9zIGFncm9wZWN1YXJpb3MgeSBmb3Jlc3RhbGVzIGVuIGdlbmVyYWwsIHNlIGRlZGljYXLDoSBhIGxhIGV4cGxvdGFjacOzbiBkZSBhY3RpdmlkYWRlcyBhZ3JvaW5kdXN0cmlhbGVzIHkgZGVtw6FzIGFmaW5lcyB5IGNvbmV4YXMgZW4gdG9kb3MgbG9zIHNlY3RvcmVzLiBQYXLDoWdyYWZvOiBwZXNlIGEgbGEgZGVzY3JpcGNpw7NuIGFudGVyaW9yLCBsYSBzb2NpZWRhZCBwb2Ryw6EgcmVhbGl6YXIgY3VhbHF1aWVyIGFjdGl2aWRhZCBjb21lcmNpYWwgbyBjaXZpbCBsaWNpdGEu",
    "Objeto social: La sociedad tiene por objeto la producción, industrialización y comercialización de productos agropecuarios y forestales en general, se dedicará a la explotación de actividades agroindustriales y demás afines y conexas en todos los sectores. Parágrafo: pese a la descripción anterior, la sociedad podrá realizar cualquier actividad comercial o civil licita.",
  ],
  [
    "T0JKRVRPIFNPQ0lBTDogTEEgU09DSUVEQUQgU0UgREVESUNBUkEgQSBSRUFMSVpBUiBBQ1RJVklEQURFUyBERSBDT01FUkNJTyAgTVVMVElOSVZFTCAgTyAgREUgIE1FUkNBREVPICBFTiAgUkVELCAgRU4gICBET05ERSAgIFNFIENPTUVSQ0lBTElaQVJBIENPTiBTRVJWSUNJT1MgREUgUExBTkVTIERFICBQUk9URUNDSU9OICBFWEVRVUlBTC4gQURJQ0lPTkFMTUVOVEUsIFNFIFBSRVNUQVJBIEVMIFNFUlZJQ0lPIERFIFBST1RFQ0NJT04gRVhFUVVJQUwgQUwgUFVCTElDTyBFTiBHRU5FUkFMLiBMQSBTT0NJRURBRCBQT0RSQSBMTEVWQVIgQSBDQUJPIEVOICBHRU5FUkFMLCBUT0RBUyBMQVMgT1BFUkFDSU9ORVMsIERFIENVQUxRVUlFUiBOQVRVUkFMRVpBIFFVRSBFTExBUyBGVUVSRU4sIEFTSSBDT01PIENVQUxRVUlFUiBBQ1RJVklEQUQgU0lNSUxBUiwgQ09ORVhBIE8gQ09NUExFTUVOVEFSSUEgUVVFIFBFUk1JVEEgRkFDSUxJVEFSIE8gREVTQVJST0xMQVIgRUwgQ09NRVJDSU8gTyBMQSBJTkRVU1RSSUEgREUgTEEgU09DSUVEQUQuIFBBUkFHUkFGTyBQUklNRVJPOiBMQSBTT0NJRURBRCBOTyBQT0RSQSBTRVIgR0FSQU5URSBFTiBPQkxJR0FDSU9ORVMgREUgTE9TICBBRE1JTklTVFJBRE9SRVMsICBTT0NJT1MsICBOSSAgREUgIFRFUkNFUkFTIFBFUlNPTkFTLCBDT0RFVURPUkVTLCBOSSBDT0FSUkVOREFUQVJJT1MgIEVOICBDT05UUkFUT1MgIERFICBMT1MgQURNSU5JU1RSQURPUkVTLCBTT0NJT1MsIE5JIERFIFRFUkNFUkFTIFBFUlNPTkFTLCBTQUxWTyAgUVVFICBMTyBBVVRPUklDRSBFWFBSRVNBTUVOVEUgTEEgQVNBTUJMRUEgR0VORVJBTCBERSBBQ0NJT05JU1RBUywgU0lFTVBSRSBZIENVQU5ETyBURU5HQU4gUkVMQUNJT04gRElSRUNUQSBDT04gTEEgQUNUSVZJREFEIFBSSU5DSVBBTCBERSBMQSBDT01QQcORSUEuICBOSU5HVU5PICBERSAgTE9TICBTT0NJT1MgIFBPRFJBICAgU0VSICAgQ09ERVVET1IgICBERSBPQkxJR0FDSU9ORVMgREUgVEVSQ0VST1MsIFNBTFZPIFFVRSBTRSBUUkFURSBERSBPQkxJR0FDSU9ORVMgREVMIENPTllVR0UgTyBERSBQQVJJRU5URVMgREVOVFJPIERFTCBQUklNRVIgIEdSQURPICBERSAgTE9TICBNSVNNT1MgU09DSU9TIERFIExBIENPTVBBw5FJQSAgWSAgUVVFICBMQSAgQVNBTUJMRUEgIERFICBBQ0NJT05JU1RBUyAgTE8gQVBSVUVCRS4gUEFSQUdSQUZPOiBMQSBFTVBSRVNBICBFSkVSQ0VSQSAgU1UgIE9CSkVUTyAgREUgIE1BTkVSQSBESVJFQ1RBLCBPIEEgVFJBVkVTIERFIFRFUkNFUk9TIE8gRU4gQ09OVkVOSU9TIENPTiBFTExPUy4NCg0KDQoNCg0KDQoNCg0KDQoNCg0KDQoNCg0KDQoNCg0KDQpDRVJUSUZJQ0E6IFFVRSBFU1RBIFNPQ0lFREFEIERFU0FSUk9MTEEgIEFDVElWSURBREVTICBERU5PTUlOQURBUyBERSBNVUxUSU5JVkVMIE8gREUgTUVSQ0FERU8gRU4gUkVELg==",
    "OBJETO SOCIAL: LA SOCIEDAD SE DEDICARA A REALIZAR ACTIVIDADES DE COMERCIO  MULTINIVEL  O  DE  MERCADEO  EN  RED,  EN   DONDE   SE COMERCIALIZARA CON SERVICIOS DE PLANES DE  PROTECCION  EXEQUIAL. ADICIONALMENTE, SE PRESTARA EL SERVICIO DE PROTECCION EXEQUIAL AL PUBLICO EN GENERAL. LA SOCIEDAD PODRA LLEVAR A CABO EN  GENERAL, TODAS LAS OPERACIONES, DE CUALQUIER NATURALEZA QUE ELLAS FUEREN, ASI COMO CUALQUIER ACTIVIDAD SIMILAR, CONEXA O COMPLEMENTARIA QUE PERMITA FACILITAR O DESARROLLAR EL COMERCIO O LA INDUSTRIA DE LA SOCIEDAD. PARAGRAFO PRIMERO: LA SOCIEDAD NO PODRA SER GARANTE EN OBLIGACIONES DE LOS  ADMINISTRADORES,  SOCIOS,  NI  DE  TERCERAS PERSONAS, CODEUDORES, NI COARRENDATARIOS  EN  CONTRATOS  DE  LOS ADMINISTRADORES, SOCIOS, NI DE TERCERAS PERSONAS, SALVO  QUE  LO AUTORICE EXPRESAMENTE LA ASAMBLEA GENERAL DE ACCIONISTAS, SIEMPRE Y CUANDO TENGAN RELACION DIRECTA CON LA ACTIVIDAD PRINCIPAL DE LA COMPAÑIA.  NINGUNO  DE  LOS  SOCIOS  PODRA   SER   CODEUDOR   DE OBLIGACIONES DE TERCEROS, SALVO QUE SE TRATE DE OBLIGACIONES DEL CONYUGE O DE PARIENTES DENTRO DEL PRIMER  GRADO  DE  LOS  MISMOS SOCIOS DE LA COMPAÑIA  Y  QUE  LA  ASAMBLEA  DE  ACCIONISTAS  LO APRUEBE. PARAGRAFO: LA EMPRESA  EJERCERA  SU  OBJETO  DE  MANERA DIRECTA, O A TRAVES DE TERCEROS O EN CONVENIOS CON ELLOS.\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "\r\n" +
      "CERTIFICA: QUE ESTA SOCIEDAD DESARROLLA  ACTIVIDADES  DENOMINADAS DE MULTINIVEL O DE MERCADEO EN RED.",
  ],
  [
    "IExhIGVtcHJlc2EgdGUwZHLhIGNvbW8gb2JqZXRvIHByaW5jaXBhbCBsYSBwcm9kdWNjafNuIGFncm9wZWN1YXJpYSwgZW4gZXNwZWNpYWwgbGEgY3LtYSBkZSBnYW5hZG8gcG9yY2lubyB5IGRlbeFzIGVzcGVjaWVzIG1lbm9yZXMsIGVsIGRlc2Fycm9sbG8gZGUgYWN0aXZpZGFkZXMgY29tZXJjaWFsZXMgeSBjb21lcmNpYWxpemFjafNuIGRlIGxvcyBwcm9kdWN0b3MgcXVlIGhhIGJpZW4gc2UgZGVzYXJyb2xsZW4geSBzZSBjcmVhbiBlbiBsYSBlbXByZXNhOyBBc+0gbWlzbW8sIHBvZHLhIHJlYWxpemFyIGN1YWxxdWllciBvdHJhIGFjdGl2aWRhZCBlY29u821pY2EgbO1jaXRhIHRhbnRvIGVuIENvbG9tYmlhIGNvbW8gZW4gZWwgZXh0cmFuamVyby4gTGEgc29jaWVkYWQgcG9kcuEgbGxldmFyIGEgY2FibyBlbiBnZW5lcmFsLCB0b2RhcyBsYXMgb3BlcmFjaW9uZXMgZGUgY3VhbHF1aWVyIG5hdHVyYWxlemEgcXVlIGVsbGFzIGZ1ZXJlbiwgcmVsYWNpb25hZGFzIGNvbiBlbCBvYmpldG8gbWVuY2lvbmFkbywgYXPtIGNvbW8gY3VhbGVzcXVpZXJhIGFjdGl2aWRhZGVzIHNpbWlsYXJlcywgY29uZXhhcyBPIGNvbXBsZW1lbnRhcmlhcyBvIHF1ZSBwZXJtaXRhbiBmYWNpbGl0YXIgbyBkZXNhcnJvbGxhciBlbCBjb21lcmNpbyBvIGxhIGluZHVzdHJpYSBkZSBsYSBzb2NpZWRhZC4N",
    "La empresa te0drá como objeto principal la producción agropecuaria, en especial la cría de ganado porcino y demás especies menores, el desarrollo de actividades comerciales y comercialización de los productos que ha bien se desarrollen y se crean en la empresa; Así mismo, podrá realizar cualquier otra actividad económica lícita tanto en Colombia como en el extranjero. La sociedad podrá llevar a cabo en general, todas las operaciones de cualquier naturaleza que ellas fueren, relacionadas con el objeto mencionado, así como cualesquiera actividades similares, conexas O complementarias o que permitan facilitar o desarrollar el comercio o la industria de la sociedad.",
  ],
];

test.each(tests)("decode %s", (encoded, decoded) => {
  expect(decodeBase64(encoded)).toBe(decoded);
});
