export const companyStatus = {
  ACTIVA: "01",
  INACTIVA: "02",
  CANCELADA: "03",
  NO_COMPETENCIA_DE_LA_CAMARA: "04",
  NO_ASIGNADO: "05",
  NO_MATRICULADO: "06",
  MATRICULA_NUEVA_CONSTITUCION_POR_TRASLADO: "07",
  MATRICULA_CANCELADA_POR_TRASLADO_DE_DOMICILIO: "09",
  MATRICULA_CANCELADA_POR_FUSION: "10",
  MATRICULA_CANCELADA_POR_RECONSTITUCION: "13",
  SIN_ESTADO: "14",
  MATRICULA_CANCELADA_LEY_1429: "15",
  MATRICULA_INACTIVA_POR_PERDIDA_DE_CALIDAD_DE_COMERCIANTE: "16",
};

export const legalEntity = {
  UNDEFINED: "00", // "00" has no corresponding description
  PERSONA_NATURAL: "01",
  SOCIEDAD_LIMITADA: "03",
  SOCIEDAD_ANONIMA: "04",
  SOCIEDAD_COLECTIVA: "05",
  SOCIEDAD_EN_COMANDITA_SIMPLE: "06",
  SOCIEDAD_EN_COMANDITA_POR_ACCIONES: "07",
  SOCIEDAD_EXTRANJERA: "08",
  EMPRESAS_ASOCIATIVAS_DE_TRABAJO: "09",
  EMPRESAS_UNIPERSONALES: "10",
  SOCIEDAD_AGRARIA_DE_TRANSFORMACION: "11",
  OTRAS_SOCIEDADES: "12",
  EMPRESAS_INDUSTRIALES_Y_COMERCIALES_DEL_ESTADO: "13",
  SOCIEDADES_POR_ACCIONES_SIMPLIFICADAS_SAS: "16",
  JUNTAS_DE_ACCION_COMUNAL: "21",
  ENTIDADES_DE_NATURALEZA_COOPERATIVA: "22",
  FONDO_DE_EMPLEADOS: "23",
  ASOCIACIONES_MUTUALES: "24",
  INSTITUCIONES_AUXILIARES_DEL_COOPERATIVISMO: "25",
  ENTIDADES_AMBIENTALISTAS: "26",
  ENTIDADES_CIENTIFICAS_TECNOLOGICAS_CULTURALES_E_INVESTIGATIVAS: "27",
  ASOCIACIONES_DE_COPROPIETARIOS_COARRENDATARIOS: "28",
  ASOCIACIONES_AGROPECUARIAS_Y_CAMPESINAS_NACIONALES_Y_NO_NACIONALES: "29",
  ASOCIACIONES_DE_PADRES_DE_FAMILIA: "30",
  CORPORACIONES: "31",
  FUNDACIONES: "32",
  LAS_DEMAS_ORGANIZACIONES_CIVILES_CORPORACIONES_FUNDACIONES: "33",
  VEEDURIA: "34",
  ASOCIACIONES_CORPORACIONES_FUNDACIONES_E_INSTITUCIONES_DE_UTILIDAD_COMUN:
    "35",
  ENTIDADES_CUYO_OBJETO_SEA_EL_DESARROLLO_DE_PLANES_Y_PROGRAMAS_DE_VIVIENDA_DE_INTERES_SOCIAL:
    "36",
  ASOCIACIONES_DE_INSTITUCIONES_EDUCATIVAS: "37",
  ASOCIACIONES_SIN_ANIMO_DE_LUCRO_O_DE_ECONOMIA_SOLIDARIA_FORMADAS_POR_PADRES_DE_FAMILIA_Y_EDUCADORES:
    "38",
  CORPORACIONES_ASOCIACIONES_Y_FUNDACIONES_CREADAS_PARA_ADELANTAR_ACTIVIDADES_EN_COMUNIDADES_INDIGENAS:
    "39",
  COOPERATIVAS_FEDERACIONES_Y_CONFEDERACIONES_INSTITUCIONES_AUXILIARES_DE_LA_ECONOMIA_SOLIDARIA_Y_PRECOOPERATIVAS:
    "40",
  EMPRESAS_DE_SERVICIOS_EN_LAS_FORMAS_DE_ADMINISTRACIONES_PUBLICAS_COOPERATIVAS:
    "41",
  ORGANIZACIONES_POPULARES_DE_VIVIENDA: "42",
  ORGANIZACIONES_EXTRANJERAS_NO_GUBERNAMENTALES_CON_DOMICILIO_EN_EL_EXTERIOR:
    "43",
};

export const registryCategoryCode = {
  PERSONA_NATURAL: "00",
  SOCIEDAD_O_PERSONA_JURIDICA_PRINCIPAL_O_ESAL: "01",
};

export const companyType = {
  NO_APLICA: "00",
  SOCIEDAD_CIVIL: "01",
  SOCIEDAD_COMERCIAL: "02",
  EMPRESAS_INDUSTRIALES_Y_COMERCIALES_DEL_ESTADO: "03",
  ENTIDAD_SIN_ANIMO_DE_LUCRO: "04",
  ENTIDAD_SIN_ANIMO_DE_LUCRO_EXTRANJERAS: "05",
  VENDEDORES_DE_JUEGOS_DE_SUERTE_Y_AZAR: "06",
  VEEDURIAS_CIUDADANAS: "07",
  ECONOMIA_SOLIDARIA: "08",
};

export const idType = {
  CEDULA_DE_CIUDADANIA: "01",
  NIT: "02",
  CEDULA_DE_EXTRANJERIA: "03",
  TARJETA_DE_IDENTIDAD: "04",
  PASAPORTE: "05",
  SIN_IDENTIFICACION: "06",
  REGISTRO_CIVIL_DE_NACIMIENTO: "07",
  DOCUMENTO_EXTRANJERO: "08",
};
