import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-sky-900 text-white">
          <h1 className="text-2xl font-bold text-center py-4 tracking-widest uppercase">
            Registro Empresarial
          </h1>
        </header>
        <div className="max-w-2xl mx-auto px-4 md:px-0 py-8">{children}</div>
      </body>
    </html>
  );
}
