import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Nit } from "@/app/Nit";
import { montserrat, roboto_flex } from "@/app/fonts";
import { Logo } from "@/app/Logo";

export const metadata: Metadata = {
  title: "NIT Empresarial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es-CO"
      className={`${roboto_flex.variable} ${montserrat.variable}`}
    >
      <body>
        <div className="bg-brand/5 text-brand">
          <div className="mx-auto flex max-w-2xl items-center justify-between px-4 py-2 md:px-0">
            <div>
              <Link href="/">
                <Logo />
              </Link>
            </div>
            <Nit className="font-bold tracking-wide" />
          </div>
        </div>
        <main className="mx-auto max-w-2xl px-4 md:px-0">{children}</main>
      </body>
    </html>
  );
}
