import { Container } from "@/app/(search)/components/Container";
import { Badge } from "@/app/[company]/components/Badge";
import { CompanyDetails } from "@/app/[company]/components/CompanyDetails";
import { EconomicActivity } from "@/app/[company]/components/EconomicActivity";
import { Section } from "@/app/[company]/components/Section";
import { getRuesDataByNit } from "@/app/[company]/services/rues";
import { siisApi } from "@/app/[company]/services/siis";
import { companiesRepository } from "@/app/db/repositories/companies";
import { formatNit } from "@/app/lib/format-nit";
import { isValidNit } from "@/app/lib/is-valid-nit";
import { parseCompanyPathSegment } from "@/app/lib/parse-company-path-segment";
import { slugifyCompanyName } from "@/app/lib/slugify-company-name";
import type { File } from "@mauriciorobayo/rues-api";
import { formatDistanceToNowStrict } from "date-fns";
import { es } from "date-fns/locale";
import type { Metadata } from "next";
import { unstable_cache } from "next/cache";
import { notFound, permanentRedirect } from "next/navigation";
import { after } from "next/server";
import { cache } from "react";

interface PageProps {
  params: Promise<{ company: string }>;
}

export const dynamic = "force-static";

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { company } = await params;
  const companyData = await getPageData(company);

  return {
    title: `${companyData.name} - NIT ${companyData.fullNit}`,
    // description: "Generated by create next app",
  };
}

export default async function page({ params }: PageProps) {
  const { company } = await params;
  const companyData = await getPageData(company);

  return (
    <article
      itemScope
      itemType="https://schema.org/Organization"
      className="mb-16 flex w-full flex-col gap-8"
    >
      <header className="flex flex-col gap-0 border-t-2 border-slate-200 bg-slate-100 sm:gap-2">
        <Container className="my-8">
          <h1
            itemProp="name"
            className="text-balance text-xl font-semibold text-brand sm:text-2xl"
          >
            {companyData.name}
          </h1>
          <div className="flex items-center gap-2">
            <h2 className="text-base text-slate-500 sm:text-lg">
              NIT: {companyData.fullNit}
            </h2>
            <Badge
              status={companyData.isActive ? "success" : "error"}
              type="color"
            >
              {companyData.isActive ? "ACTIVA" : "CANCELADA"}
            </Badge>
          </div>
        </Container>
      </header>
      <Container className="mx-auto grid max-w-4xl grid-flow-row-dense grid-cols-1 gap-6 sm:grid-cols-2">
        <Section id="detalles-de-la-empresa">
          <Section.title>Detalles de la Empresa</Section.title>
          <CompanyDetails details={companyData.details} />
          <EconomicActivity
            economicActivities={companyData.economicActivities}
          />
        </Section>
        <div className="contents flex-col sm:flex sm:gap-6">
          <Section id="camara-de-comercio">
            <Section.title>Cámara de Comercio</Section.title>
            <CompanyDetails details={companyData.chamber} />
          </Section>
          {companyData.businessEstablishments.length > 0 && (
            <Section id="establecimientos-comerciales">
              <Section.title>Establecimientos Comerciales</Section.title>
              {companyData.businessEstablishments.map((establishment) => {
                return (
                  <details key={establishment.id}>
                    <summary>{establishment.name}</summary>
                    <CompanyDetails details={establishment.details} />
                  </details>
                );
              })}
            </Section>
          )}
        </div>
      </Container>
    </article>
  );
}

const getCompanyData = unstable_cache(
  cache(async (nit: number) => {
    const [companyData, siis] = await Promise.all([
      getRuesDataByNit(nit),
      siisApi(nit),
    ]);

    if (!companyData?.rues) {
      return null;
    }

    after(async () => {
      await companiesRepository.upsert({
        nit,
        name: companyData.rues.razon_social,
      });
    });

    const registrationDate = gatDateFromDetailsDate(
      companyData.details?.["fecha_matricula"],
    );

    return {
      name: companyData.rues.razon_social,
      nit: companyData.rues.nit,
      fullNit: formatNit(Number(companyData.rues.nit)),
      isActive: companyData.rues.estado_matricula === "ACTIVA",
      details: [
        {
          label: "Razón social",
          value: companyData.rues["razon_social"],
        },
        { label: "NIT", value: companyData.rues["nit"] },
        { label: "DV", value: companyData.rues["dv"] },
        {
          label: "Matrícula",
          value: companyData.rues["matricula"],
        },
        { label: "Sigla", value: companyData.rues["sigla"] },
        {
          label: "Organización jurídica",
          value: companyData.rues["organizacion_juridica"],
        },
        {
          label: "Estado",
          value: companyData.rues["estado_matricula"],
        },
        {
          label: "Fecha de creación",
          value: registrationDate,
        },
        {
          label: "Antigüedad",
          value: getYearsOfBusiness(registrationDate),
        },
        {
          label: "Fecha de renovación",
          value: gatDateFromDetailsDate(
            companyData.details?.["fecha_renovacion"],
          ),
        },
        {
          label: "Fecha de actualización",
          value: gatDateFromDetailsDate(
            companyData.details?.["fecha_actualizacion"],
          ),
        },
        {
          label: "Fecha de cancelación",
          value: gatDateFromDetailsDate(
            companyData.details?.["fecha_cancelacion"],
          ),
        },
        {
          label: "Último año renovado",
          value: companyData.details?.["ultimo_ano_renovado"],
        },
        {
          label: "Indicador de emprendimiento social",
          value: companyData.details?.["indicador_emprendimiento_social"],
        },
        {
          label: "Tipo de sociedad",
          value: companyData.details?.["tipo_sociedad"],
        },
        {
          label: "Extinción de dominio",
          value: companyData.details?.["extincion_dominio"],
        },
        { label: "Región", value: siis?.["region"] },
        { label: "Departamento", value: siis?.["departamento"] },
        { label: "Ciudad", value: siis?.["ciudad"] },
        { label: "Macro sector", value: siis?.["macroSector"] },
        { label: "Sector", value: siis?.["sector"] },
      ],
      economicActivities: getEconomicActivitiesFromDetails(companyData.details),
      chamber: [
        { label: "Nombre", value: companyData.chamber?.["name"] },
        { label: "Dirección", value: companyData.chamber?.["address"] },
        { label: "Ciudad", value: companyData.chamber?.["city"] },
        { label: "Departamento", value: companyData.chamber?.["state"] },
        {
          label: "Certificado de tradición",
          value: {
            url: companyData.details?.["url_venta_certificados"],
            label: "Descargar certificado de tradición en línea",
          },
        },
      ],
      businessEstablishments: (companyData.establishments ?? []).map(
        (establishment) => {
          const creationDate = gatDateFromDetailsDate(
            establishment["FECHA_MATRICULA"],
          );
          return {
            name: establishment["RAZON_SOCIAL"],
            id: establishment["MATRICULA"],
            details: [
              {
                label: "Razón social",
                value: establishment["RAZON_SOCIAL"],
              },
              {
                label: "Sigla",
                value: establishment["SIGLA"],
              },
              {
                label: "Matrícula",
                value: establishment["MATRICULA"],
              },
              {
                label: "Tipo de sociedad",
                value: establishment["DESC_TIPO_SOCIEDAD"],
              },
              {
                label: "Organización jurídica",
                value: establishment["DESC_ORGANIZACION_JURIDICA"],
              },
              {
                label: "Categoría",
                value: establishment["CATEGORIA_MATRICULA"],
              },
              {
                label: "Estado",
                value: establishment["DESC_ESTADO_MATRICULA"],
              },
              {
                label: "Fecha de constitución",
                value: creationDate,
              },
              {
                label: "Antigüedad",
                value: getYearsOfBusiness(creationDate),
              },
              {
                label: "Fecha de renovación",
                value: gatDateFromDetailsDate(
                  establishment["FECHA_RENOVACION"],
                ),
              },
              {
                label: "Último año renovado",
                value: establishment["ULTIMO_ANO_RENOVADO"],
              },
            ],
          };
        },
      ),
    };
  }),
);

function getYearsOfBusiness(date?: Date) {
  return date
    ? formatDistanceToNowStrict(date, {
        locale: es,
      })
    : undefined;
}

function getEconomicActivitiesFromDetails(details: File | undefined) {
  if (!details) {
    return [];
  }
  const economicActivities = [
    {
      code: details["cod_ciiu_act_econ_pri"],
      description: details["desc_ciiu_act_econ_pri"],
    },
  ];

  if (details["cod_ciiu_act_econ_sec"] && details["desc_ciiu_act_econ_sec"]) {
    economicActivities.push({
      code: details["cod_ciiu_act_econ_sec"],
      description: details["desc_ciiu_act_econ_sec"],
    });
  }

  if (details["ciiu3"] && details["desc_ciiu3"]) {
    economicActivities.push({
      code: details["ciiu3"],
      description: details["desc_ciiu3"],
    });
  }

  if (details["ciiu4"] && details["desc_ciiu_act_econ_sec"]) {
    economicActivities.push({
      code: details["ciiu4"],
      description: details["desc_ciiu4"],
    });
  }

  return economicActivities;
}

function gatDateFromDetailsDate(value?: string) {
  if (!value?.trim() || value.length !== 8) {
    return undefined;
  }
  const formattedDate = `${value.slice(0, 4)}-${value.slice(4, 6)}-${value.slice(6, 8)}`;
  const date = new Date(formattedDate);
  return Number.isNaN(date.getTime()) ? undefined : date;
}

// This function is unintentionally not cached so we can handle logic based
// on the segmentPath which can be different given the same nit:
//   - rnit.co/930123456
//   - rnit.co/razon-social-930123456
//   - rnit.co/razon-social-cambio-930123456
// all of the above should trigger this uncached logic to do proper redirects
// Get DO cache fetching the data based on the NIT, so we avoid doing requests
// to the APIs given the same NIT if we already got the data.
async function getPageData(company: string) {
  const { nit, slug } = parseCompanyPathSegment(company);

  if (!isValidNit(nit)) {
    notFound();
  }

  // Cache at the NIT level to avoid multiple path segments with same NIT
  // triggering multiple duplicated API calls
  const companyData = await getCompanyData(nit);

  if (!companyData) {
    notFound();
  }

  const companySlug = slugifyCompanyName(companyData.name);

  if (slug !== companySlug) {
    permanentRedirect(`${companySlug}-${nit}`);
  }

  return companyData;
}
